services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: RetailCRM_Radis
    environment:
      - RETAILCRM_API_KEY=gMTqWW6Atdsf11V7vYwcAbnmhBVQEHWf
      - PROJECT_NAME=RetailCRM_API_Redis_Test
      - PROJECT_VERSION=1.0.0
    # ports:  # НЕ НУЖНО!
    #   - "8090:80"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost/docs" ]
      interval: 5s
      timeout: 20s
      retries: 10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`test.radisby.ru`)"
      - "traefik.http.routers.myapp.entrypoints=http,https"
      - "traefik.http.routers.myapp.tls=true"
      - "traefik.http.services.myapp.loadbalancer.server.port=80"